FROM node:20-alpine3.19
ARG NEXT_PUBLIC_VERSION
ENV NEXT_PUBLIC_VERSION=$NEXT_PUBLIC_VERSION
RUN apk add --no-cache g++ make py3-pip supervisor bash caddy curl
RUN npm --no-update-notifier --no-fund --global install pnpm@10.6.1 pm2

WORKDIR /app

COPY . /app
COPY var/docker/supervisord.conf /etc/supervisord.conf
COPY var/docker/Caddyfile /app/Caddyfile
COPY var/docker/entrypoint.sh /app/entrypoint.sh
COPY var/docker/supervisord/caddy.conf /etc/supervisor.d/caddy.conf
RUN chmod +x /app/entrypoint.sh

# Install dependencies
RUN pnpm install

# Build with increased Node.js memory limit and build apps sequentially
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN pnpm run build:backend && rm -rf /tmp/* 
RUN pnpm run build:frontend && rm -rf /tmp/*
RUN pnpm run build:workers && rm -rf /tmp/*
RUN pnpm run build:cron && rm -rf /tmp/*

EXPOSE 5000

CMD ["pnpm", "run", "pm2"]
